name: pr-workflow

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  pr-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Lint
        run: npm run lint
      - name: Tests
        run: npm run test
